remote_theme: mmistakes/so-simple-theme
email: p.gildersleve@lse.ac.uk
title: ""
description: ""
#logo: images/PG.jpg
twitter:
  username: pgildersleve
github_username: pgilders

Patrick_Gildersleve: 
  name: Patrick Gildersleve
  picture: images/PG.jpg
  avatar: images/PG.jpg
  email: p.gildersleve@lse.ac.uk
  twitter: pgildersleve
  links:
author: Patrick_Gildersleve
