remote_theme: mmistakes/so-simple-theme
email: patrick.gildersleve@oii.ox.ac.uk
title: Patrick Gildersleve
description: 
#logo: images/PG.jpg
twitter:
  username: pgildersleve
github_username: pgilders

Patrick_Gildersleve: 
  name: Patrick Gildersleve
  picture: images/PG.jpg
  avatar: images/PG.jpg
  email: patrick.gildersleve@oii.ox.ac.uk
  twitter: pgildersleve
  links:
    - title: test123
      url: bbc.com
      icon: images/PG.jpg
author: Patrick_Gildersleve
