theme: jekyll-theme-dinky
title: Patrick Gildersleve
email: patrick.gildersleve@oii.ox.ac.uk
description: Personal website for Patrick Gildersleve, DPhil Candidate at the Oxford Internet Institute
twitter_username: pgildersleve
github_username: pgilders
